fte_odds_dict = {'Lens': 'Lens', 'Lille': 'Lille', 'Saint-Étienne': 'St Etienne', 'Bordeaux': 'Bordeaux', 'Nice': 'Nice', 'Monaco': 'AS Monaco', 'Angers': 'Angers', 'Nantes': 'Nantes', 'Reims': 'Reims', 'Lorient': 'Lorient', 'Clermont': 'Clermont Foot', 'Brest': 'Brest', 'Troyes': 'Troyes', 'Montpellier': 'Montpellier', 'Marseille': 'Marseille', 'Rennes': 'Stade Rennes', 'Paris SG': 'Paris Saint-Germain', 'Lyon': 'Lyon', 'Strasbourg': 'Strasbourg', 'Metz': 'Metz', 'Burnley': 'Burnley', 'Arsenal': 'Arsenal', 'Norwich City': 'Norwich City', 'Watford': 'Watford', 'Manchester City': 'Manchester City', 'Southampton': 'Southampton', 'Liverpool': 
'Liverpool', 'Crystal Palace': 'Crystal Palace', 'Aston Villa': 'Aston Villa', 'Everton': 'Everton', 'Brighton': 'Brighton and Hove Albion', 'Leicester City': 'Leicester City', 'West Ham': 'West Ham United', 'Manchester United': 'Manchester United', 'Tottenham': 'Tottenham Hotspur', 'Chelsea': 'Chelsea', 'Newcastle': 'Newcastle', 'Leeds United': 'Leeds United', 'Brentford': 'Brentford', 'Wolves': 'Wolverhampton', 'Rayo Vallecano': 'Rayo Vallecano', 'Getafe': 'Getafe', 'Atlético Madrid': 'Atletico Madrid', 'Athletic Club Bilbao': 'Athletic Bilbao', 'Elche': 'Elche', 'Levante': 'Levante', 'Alavés': 'Alavés', 'Osasuna': 'Osasuna', 'Mallorca': 'Mallorca', 'Villarreal': 'Villarreal', 'Real Sociedad': 'Real Sociedad', 'Sevilla': 'Sevilla FC', 'Real Betis': 'Real Betis', 'Espanyol': 'Espanyol', 'Valencia': 'Valencia', 'Real Madrid': 'Real Madrid', 'FC Barcelona': 'Barcelona', 'Granada CF': 'Granada', 'Celta Vigo': 'Celta Vigo', 'Cadiz': 'Cadiz', 'Genoa': 'Genoa', 'Fiorentina': 'Fiorentina', 'Inter': 'Internazionale', 'Bologna': 'Bologna', 'Salernitana': 'Salernitana', 'Atalanta': 'Atalanta', 'Empoli': 'Empoli', 'Sampdoria': 'Sampdoria', 'Venezia': 'F.B.C Unione Venezia', 'Spezia': 'Spezia', 'Hellas Verona': 'Verona', 'Roma': 'AS Roma', 'Lazio': 'Lazio', 'Cagliari': 'Cagliari', 'Juventus': 'Juventus', 'AC Milan': 'AC Milan', 'Udinese': 'Udinese', 'Napoli': 'Napoli', 'Mainz 05': 'Mainz', 'SC Freiburg': 'SC Freiburg', 'FC Augsburg': 'FC Augsburg', 'Borussia Mönchengladbach': 'Borussia Monchengladbach', 'Bayern Munich': 'Bayern Munich', 'VfL Bochum': 'VfL Bochum', 'Arminia Bielefeld': 'Arminia Bielefeld', 'TSG Hoffenheim': 'TSG Hoffenheim', '1. FC Köln': 'FC Cologne', 'RB Leipzig': 'RB Leipzig', 'VfB Stuttgart': 'VfB Stuttgart', 'Bayer Leverkusen': 'Bayer Leverkusen','NEC Nijmegen': 'NEC', 'Borussia Dortmund': 'Borussia Dortmund', '1. FC Union Berlin': '1. FC Union Berlin', 'VfL Wolfsburg': 'VfL Wolfsburg', 'Eintracht Frankfurt': 'Eintracht Frankfurt', 'Greuther Fürth': 'SpVgg Greuther Fürth', 'Hertha BSC': 'Hertha Berlin', 'Atlanta United FC': 'Atlanta United FC', 'DC United': 'DC United', 'NE Revolution': 'New England Revolution', 'COL Crew': 'Columbus Crew', 'Toronto FC': 'Toronto FC', 'Nashville SC': 'Nashville SC', 'FC Cincinnati': 'FC Cincinnati', 'NYCFC': 'New York City FC', 'Austin FC': 'Austin FC', 'SJ Earthquakes': 'San Jose Earthquakes', 'MIN United': 'MIN United', 'LA Galaxy': 'LA Galaxy II', 'Real Salt Lake': 'Real Salt Lake', 'SEA Sounders': 'Seattle Sounders FC', 'HOU Dynamo': 'Houston Dynamo', 'FC Dallas': 
'FC Dallas', 'CF Montreal': 'Montreal Impact', 'CHI Fire': 'Chicago Fire', 'PHI Union': 'Philadelphia Union', 'ORL City SC': 'Orlando City SC', 'POR Timbers': 'Portland Timbers', 'Los Angeles FC': 'Los Angeles FC', 'COL Rapids': 'Colorado Rapids', 'VAN Whitecaps FC': 'Vancouver Whitecaps', 'Club León': 'León', 'FC Juárez': 'FC Juárez', 'Deportivo Toluca FC': 'Toluca', 'Club América': 'Club América', 'Chivas Guadalajara': 'Guadalajara', 'CF Pachuca': 'Pachuca', 'Mazatlán FC': 'Mazatlán FC', 'Pumas UNAM': 'Pumas Unam', 'Cruz Azul': 'Cruz Azul', 'Querétaro FC': 'Querétaro', 'CF Monterrey': 'Monterrey', 'Tigres UANL': 'Tigres UANL', 'Santos Laguna': 'Santos Laguna', 'Puebla FC': 'Puebla', 'Atlético San Luis': 'Atlético San Luis', 'Club Necaxa': 'Necaxa', 'Club Tijuana': 'Tijuana', 'Club Atlas': 'Atlas', 'Werder Bremen': 
'Werder Bremen', 'Hamburger SV': 'Hamburg SV', 'Darmstadt 98': 'SV Darmstadt 98', 'Dynamo Dresden': 'Dynamo Dresden', 'FC St. Pauli': 'FC St. Pauli', 'FC Ingolstadt 04': 'FC Ingolstadt 04', 'Erzgebirge Aue': 'Erzgebirge Aue', 'SC Paderborn 07': 'SC Paderborn', 'Fulham': 'Fulham', 'Reading': 'Reading', 'Derby County': 'Derby County', 'Stoke City': 'Stoke City', 'Huddersfield Town': 'Huddersfield Town', 'Nottingham Forest': 'Nottingham Forest', 'Cardiff City': 'Cardiff City', 'Bournemouth': 'AFC Bournemouth', 'Barnsley': 'Barnsley', 'Blackburn Rovers': 'Blackburn', 'Queens Park Rangers': 'Queens Park Rangers', 'Bristol City': 'Bristol City', 'Preston North End': 'Preston North End', 'West Bromwich': 'West Bromwich Albion', 'Middlesbrough': 'Middlesbrough', 'Blackpool': 'Blackpool', 'Luton Town': 'Luton Town', 
'Swansea City': 'Swansea City', 'Peterborough United': 'Peterborough United', 'Birmingham': 'Birmingham', 'Millwall': 'Millwall', 'Coventry City': 'Coventry City', 'Hull City': 'Hull City', 'Sheffield United': 'Sheffield United', 'Famalicão': 'Famalicao', 'Marítimo Funchal': 'Maritimo', 'Belenenses': 'Belenenses', 'Gil Vicente': 'Gil Vicente', 'Arouca': 'FC Arouca', 'Vitoria Guimarães': 'Guimaraes', 'Vizela': 'Vizela', 
'Paços Ferreira': 'Pacos Ferreira', 'FC Porto': 'FC Porto', 'Moreirense': 'Moreirense', 'Estoril': 'Estoril Praia', 'Sporting Lisbon': 'Sporting CP', 'Benfica': 'Benfica', 'Boavista': 'Boavista', 'S.C. Braga': 'Braga', 'CD de Tondela': 'Tondela', 'Reggina': 'Reggina', 'Spal': 'Spal', 'Monza': 'Monza', 'Ternana': 'Ternana', 'Lecce': 'Lecce', 'Alessandria': 'Alessandria', 'Perugia': 'Perugia', 'Cosenza': 'Cosenza', 'Ascoli': 'Ascoli', 'Benevento': 'Benevento', 'Vicenza': 'Vicenza', 'Pisa': 'Pisa', 'Cittadella': 'Cittadella', 'Pordenone': 'Pordenone Calcio', 'Parma': 'Parma', 'Cremonese': 'Cremonese', 'Frosinone': 'Frosinone', 'Brescia': 'Brescia', 'SC Heerenveen': 'Heerenveen', 'Fortuna Sittard': 'Fortuna Sittard', 'Willem II': 'Willem II', 'FC Groningen': 'FC Groningen', 'Ajax': 'Ajax', 'Cambuur Leeuwarden': 'Cambuur Leeuwarden', 'FC Utrecht': 'FC Utrecht', 'Go Ahead Eagles': 'Go Ahead Eagles', 'PEC Zwolle': 'PEC Zwolle', 'PSV Eindhoven': 'PSV', 'Feyenoord': 'Feyenoord', 'Heracles Almelo': 'Heracles', 'AZ Alkmaar': 'AZ', 'Vitesse': 'Vitesse', 'FC Twente': 'FC Twente', 'NEC': 'FC Groningen', 'Sparta Rotterdam': 'Sparta', 'Sassuolo': 'Sassuolo', 'Alebrijes de Oaxaca': 'Talleres de Córdoba', 'RKC Waalwijk': 'RKC', 'Como': 'Como', 'Crotone': 'Crotone', 'Torino': 'Torino', 'Karlsruher SC': 'Karlsruher SC', 'Holstein Kiel': 'Holstein Kiel', 'Hannover 96': 'Hannover 96', 'SV Sandhausen': 'SV Sandhausen', '1. FC Heidenheim': '1. FC Heidenheim 1846', 'Hansa Rostock': 'Hansa Rostock', 'Fortuna Düsseldorf': 'Fortuna Düsseldorf', 'FC Schalke 04': 'Schalke 04', 'Jahn Regensburg': 'Jahn Regensburg', 
'1. FC Nürnberg': '1. FC Nürnberg', 'Sporting KC': 'Sporting Kansas City', 'Inter Miami CF': 'Inter Miami CF', 'New York Red Bulls': 'New York Red Bulls', 'Leones Negros UDG': 'Guadalajara', 'Portimonense': 'Portimonense', 'Santa Clara': 'Santa Clara'}   




# fte_odds_dict = {'Angers': 'Angers', 
#                  'Rennes': 'Stade Rennes', 
#                  'Clermont': 'Clermont Foot', 
#                  'Metz': 'Metz', 
#                  'Strasbourg': 'Strasbourg', 
#                  'Brest': 'Brest', 
#                  'Lens': 'Lens', 
#                  'Lorient': 'Lorient', 
#                  'Lille': 'Lille', 
#                  'Montpellier': 'Montpellier', 
#                  'Reims': 'Reims', 
#                  'Paris SG': 'Paris FC', 
#                  'Troyes': 'Troyes', 
#                  'Bordeaux': 'Bordeaux', 
#                  'Lyon': 'Lyon', 
#                  'Monaco': 'AS Monaco', 
#                  'Marseille': 'Marseille', 
#                  'Nantes': 'Nantes', 
#                  'Nice': 'Nice', 
#                  'Saint-Étienne': 'St Etienne', 
#                  'Burnley': 'Burnley', 
#                  'Leeds United': 'Leeds United', 
#                  'Tottenham': 'Tottenham Women', 
#                  'Watford': 'Watford', 
#                  'Wolves': 'Molde', 
#                  'Manchester United': 'Manchester United', 
#                  'Crystal Palace': 'Crystal Palace', 
#                  'Arsenal': 'Arsenal', 
#                  'Norwich City': 'Norwich City', 
#                  'Brentford': 'Brentford', 
#                  'Brighton': 'Burgos', 
#                  'Southampton': 'Southampton', 
#                  'West Ham': 'West Ham United', 
#                  'Newcastle': 'Newcastle', 
#                  'Leicester City': 'Leicester City', 
#                  'Manchester City': 'Manchester City', 
#                  'Chelsea': 'Chelsea', 
#                  'Aston Villa': 'Aston Villa', 
#                  'Liverpool': 'Liverpool',
#                   'Everton': 'Everton', 
#                   'FC Barcelona': 'Barcelona', 
#                   'Getafe': 'Getafe', 
#                   'Rayo Vallecano': 'Rayo Vallecano', 
#                   'Granada CF': 'Granada', 
#                   'Cadiz': 'Cadiz', 
#                   'Osasuna': 'Osasuna', 
#                   'Atlético Madrid': 'Atletico Madrid', 
#                   'Villarreal': 'Villarreal', 
#                   'Levante': 'Levante', 
#                   'Espanyol': 'Espanyol', 
#                   'Real Madrid': 'Real Madrid', 
#                   'Celta Vigo': 'Celta Vigo', 
#                   'Alavés': 'Alavés', 
#                   'Sevilla': 'Sevilla FC', 
#                   'Real Sociedad': 'Real Sociedad', 
#                   'Valencia': 'Valencia', 
#                   'Elche': 'Elche', 
#                   'Real Betis': 'Real Betis', 
#                   'Athletic Club Bilbao': 'Athletic Bilbao', 
#                   'Mallorca': 'Mallorca', 
#                   'Genoa': 'Genoa', 
#                   'Napoli': 'Napoli', 
#                   'Sassuolo': 'Sassuolo', 
#                   'Sampdoria': 'Sampdoria', 
#                   'Salernitana': 'Salernitana', 
#                   'Roma': 'AS Roma', 
#                   'AC Milan': 'AC Milan', 
#                   'Cagliari': 'Cagliari', 
#                   '1. FC Union Berlin': '1. FC Union Berlin', 
#                   'Borussia Mönchengladbach': 
#                   'Borussia Monchengladbach', 
#                   'VfL Wolfsburg': 'VfL Wolfsburg', 
#                   'RB Leipzig': 'RB Leipzig', 
#                   'FC Augsburg': 'FC Augsburg', 
#                   'SC Freiburg': 'SC Freiburg', 
#                  'TSG Hoffenheim': 'TSG Hoffenheim', 
#                  'Mainz 05': 'Mainz', 
#                  'Bayer Leverkusen': 'Bayer Leverkusen', 
#                  'Borussia Dortmund': 'Borussia Dortmund', 
#                  'Greuther Fürth': 'SpVgg Greuther Fürth', 
#                  'Bayern Munich': 'Bayern Munich', 
#                  'Eintracht Frankfurt': 'Eintracht Frankfurt', 
#                  'VfB Stuttgart': 'VfB Stuttgart',
#                  'VfL Bochum': 'VfL Bochum', 
#                  'Hertha BSC': 'Hertha Berlin', 
#                  'Arminia Bielefeld': 'Arminia Bielefeld', 
#                  'Alebrijes de Oaxaca': 'Talleres de Córdoba', 
#                  'Austin FC': 'Austin FC', 
#                  'FC Dallas': 'FC Dallas',
#                  'Deportivo Toluca FC': 'Toluca', 
#                  'VAN Whitecaps FC': 'Vancouver Whitecaps', 
#                  'Real Salt Lake': 'Real Salt Lake', 
#                  'SEA Sounders': 'Seattle Sounders FC', 
#                  'POR Timbers': 'Portland Timbers', 
#                  'Pumas UNAM': 'Pumas Unam', 
#                  'Santos Laguna': 'Santos Laguna', 
#                  'FC Juárez': 'FC Juárez',
#                  'RKC Waalwijk':'RKC',
#                  '1. FC Köln': 'FC Cologne',
#                  'Atlanta United FC':'Atlanta United FC',
#                  'Lecce': 'Lecce', 'Como': 'Como', 'Ascoli': 'Ascoli', 'Alessandria': 'Alessandria', 'Brescia': 'Brescia', 'Spal': 'Spal', 'Monza': 'Monza', 'Frosinone': 'Frosinone', 'Perugia': 'Perugia', 'Ternana': 'Ternana', 'Pisa': 'Pisa', 'Crotone': 'Crotone', 'Reggina': 'Reggina', 'Cosenza': 'Cosenza', 'Vicenza': 'Vicenza', 'Cremonese': 'Cremonese', 'Cittadella': 'Cittadella', 'Pordenone': 'Pordenone Calcio', 'Parma': 'Parma',
#                  'Lazio': 'Lazio', 'Roma': 'AS Roma', 'Sassuolo': 'Sassuolo', 'Cagliari': 'Cagliari', 'Genoa': 'Genoa', 'Empoli': 'Empoli', 'Venezia': 'Vicenza', 'Atalanta': 'Atalanta', 'Fiorentina': 'Fiorentina', 'Bologna': 'Bologna', 'Hellas Verona': 'Verona', 'Spezia': 'Spezia', 'Udinese': 'Udinese', 'Torino': 'Torino', 'Salernitana': 'Salernitana', 'Napoli': 'Napoli', 'Juventus': 'Juventus', 'Sampdoria': 'Sampdoria', 'Inter': 'Inter',
#                  'Empoli': 'Empoli', 
#                  'Karlsruher SC': 'Karlsruher SC', 'Holstein Kiel': 'Holstein Kiel', 'FC Ingolstadt 04': 'FC Ingolstadt 04', 'Werder Bremen': 'Werder Bremen', 'Hannover 96': 'Hannover 96', 'FC St. Pauli': 'FC St. Pauli', 'Hamburger SV': 'Hamburg SV', 'SV Sandhausen': 'SV Sandhausen', '1. FC Heidenheim': '1. FC Heidenheim 1846', 'Dynamo Dresden': 'Dynamo Dresden', 'Hansa Rostock': 'Hansa Rostock', 'Darmstadt 98': 'SV Darmstadt 98', 'Erzgebirge Aue': 'Erzgebirge Aue', 'Fortuna Düsseldorf': 'Fortuna Düsseldorf', 'SC Paderborn 07': 'SC Paderborn', 'FC Schalke 04': 'Schalke 04', 'Jahn Regensburg': 'Jahn Regensburg', '1. FC Nürnberg': '1. FC Nürnberg',
#                  'Nashville SC': 'Nashville SC',
#                  'Nashville SC': 'Nashville SC', 'NYCFC': 'New York City FC', 'PHI Union': 'Philadelphia Union', 'NE Revolution': 'New England Revolution', 'HOU Dynamo': 'Houston Dynamo', 'POR Timbers': 'Portland Timbers', 'Los Angeles FC': 'Los Angeles FC', 'Sporting KC': 'Sporting Kansas City', 'VAN Whitecaps FC': 'Vancouver Whitecaps', 'Austin FC': 'Austin FC', 'ORL City SC': 'Orlando City SC', 'COL Crew': 'Columbus Crew', 'Real Salt Lake': 'Real Salt Lake', 'FC Dallas': 'FC Dallas', 'FC Cincinnati': 'FC Cincinnati', 'Inter Miami CF': 'Inter Miami CF', 'SJ Earthquakes': 'San Jose Earthquakes', 'COL Rapids': 'Colorado Rapids', 'Puebla FC': 'Puebla', 'Atlético San Luis': 'Atlético San Luis', 
#                  'Leones Negros UDG':'Guadalajara',
#                  'Cruz Azul': 'Cruz Azul', 'CF Pachuca': 'Pachuca', 'Club Tijuana': 'Tijuana', 'Puebla FC': 'Puebla', 'Atlético San Luis': 'Atlético San Luis', 'Club Atlas': 'Atlas', 'CF Monterrey': 'Monterrey', 'Tigres UANL': 'Tigres UANL', 'Club León': 'León', 'Club América': 'Club América', 'Mazatlán FC': 'Mazatlán FC', 
#                  'Chivas Guadalajara': 'Guadalajara', 'Querétaro FC': 'Querétaro', 'Club Necaxa': 'Necaxa', 'Birmingham': 'Birmingham', 'Derby County': 'Derby County', 'West Bromwich': 'West Bromwich Albion', 'Millwall': 'Millwall', 'Swansea City': 'Swansea City', 'Hull City': 'Hull City', 'Reading': 'Reading', 'Queens Park Rangers': 'Queens Park Rangers', 'Stoke City': 'Stoke City', 'Huddersfield Town': 'Huddersfield Town', 'Sheffield United': 'Sheffield United', 'Peterborough United': 'Peterborough United', 'Bournemouth': 'AFC Bournemouth', 'Barnsley': 'Barnsley', 'Blackpool': 'Blackpool', 'Fulham': 'Fulham', 'Coventry City': 'Coventry City', 'Middlesbrough': 'Middlesbrough', 'Bristol City': 'Bristol City', 'Preston North End': 'Preston North End', 'Blackburn Rovers': 'Blackburn', 'Luton Town': 'Luton Town', 'Nottingham Forest': 'Nottingham Forest', 'Cardiff City': 'Cardiff City', 'S.C. Braga': 'Braga', 'Vitoria Guimarães': 'Guimaraes', 'Benfica': 'Benfica', 'CD de Tondela': 'Tondela', 'Portimonense': 'Portimonense', 'Paços Ferreira': 'Pacos Ferreira', 'Santa Clara': 'Santa Clara', 'Gil Vicente': 'Gil Vicente', 'Cittadella': 'Cittadella', 'Crotone': 'Crotone', 'Spal': 'Spal', 'Pordenone': 'Pordenone Calcio', 'Parma': 'Parma', 'Benevento': 'Benevento', 'Reggina': 'Reggina', 'Ternana': 'Ternana', 'Lecce': 'Lecce', 'Como': 'Como', 'Monza': 'Monza', 'Cremonese': 'Cremonese', 'SC Heerenveen': 'Heerenveen', 'AZ Alkmaar': 'Alanyaspor', 'FC Twente': 'FC Twente', 'FC Utrecht': 'FC Utrecht', 'Cambuur Leeuwarden': 'Cambuur Leeuwarden', 'Go Ahead Eagles': 'Go Ahead Eagles', 'PEC Zwolle': 'PEC Zwolle', 'Ajax': 'Ajax', 'Sparta Rotterdam': 'Sparta Prague', 'Fortuna Sittard': 'Fortuna Sittard', 'PSV Eindhoven': 'SV Sandhausen', 'NEC Nijmegen': 'NEC', 'Willem II': 'Willem II', 'Vitesse': 'Vitesse', 'Feyenoord': 'Feyenoord', 'Heracles Almelo': 'Heracles', 'FC Groningen': 'FC Groningen'}


fte_odds_dict_rev  = {v: k for k, v in fte_odds_dict.items()} 
